import FactChecker from "@/components/FactChecker";

export default function Home() {
  return (
    <div className="container mx-auto py-8">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          AI Fact Checker ✨
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Instantly verify claims using our AI-powered fact-checking tool. Simply enter a statement to receive source-backed insights generated by advanced language models.        
        </p>        
      </div>
      
      <FactChecker />
      <p className="text-sm text-gray-300 max-w-2xl mx-auto">Disclaimer: This tool uses AI to assist with fact-checking and may not always reflect the most current or accurate information. Users should independently verify critical facts from trusted sources.</p>
    </div>
  );
}
