name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test_secret:
    runs-on: ubuntu-latest
    name: Test Secret Access
    steps:
      - name: Test Secret
        run: |
          echo "Testing secret access..."
          if [ -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "✅ Secret is accessible"
            echo "Token length: $(echo '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}' | wc -c)"
          else
            echo "❌ Secret is NOT accessible"
          fi
          
          echo "All secrets available:"
          echo '${{ toJSON(secrets) }}'
